_wandb:
    value:
        cli_version: 0.25.1
        e:
            vsic2sp5kwd4ql5ud97sd0jpxe6fha3l:
                codePath: src\utils\wandbstart.py
                codePathLocal: src\utils\wandbstart.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "509904678912"
                        used: "388415164416"
                email: ksouza@ucm.es
                executable: C:\Users\ksouz\Desktop\c2526-R2\.venv\Scripts\python.exe
                git:
                    commit: 5c13e51a1b3fe6013b157d0c07885398f7288074
                    remote: https://github.com/UCM-GIDIA-PD1/c2526-R2.git
                host: Windows
                memory:
                    total: "17013497856"
                os: Windows-11-10.0.26200-SP0
                program: c:\Users\ksouz\Desktop\c2526-R2\src\utils\wandbstart.py
                python: CPython 3.12.12
                root: C:\Users\ksouz\Desktop\c2526-R2
                startedAt: "2026-03-16T15:15:55.212779Z"
                writerId: vsic2sp5kwd4ql5ud97sd0jpxe6fha3l
        m: []
        python_version: 3.12.12
        t:
            "3":
                - 2
                - 16
            "4": 3.12.12
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
